package advantageonlineshopping.com.utils;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.Comparator;

public final class ReportGenerator {

    private static final Logger log = LoggerFactory.getLogger(ReportGenerator.class);

    private ReportGenerator() {
        // Utility class
    }

    /**
     * Tries to generate an Allure HTML report after tests run.
     * Strategy:
     * 1) If 'allure' CLI is available, run: allure generate <results> -o <out> --clean
     * 2) Else try: mvn allure:report (requires mvn in PATH)
     * 3) Copy generated report to evidences/latest
     * 4) If HTML generation is not possible, copy raw results to evidences/allure-results
     */
    public static void generateAllureReport() throws IOException, InterruptedException {
        Path projectDir = Paths.get(System.getProperty("user.dir"));
        Path resultsDir = projectDir.resolve("target/allure-results");
        Path generatedReportDir = projectDir.resolve("target/site/allure-maven-plugin");
        Path evidencesLatest = projectDir.resolve("evidences/latest");
        Path evidencesResults = projectDir.resolve("evidences/allure-results");

        if (!Files.exists(resultsDir) || isDirectoryEmpty(resultsDir)) {
            log.warn("Allure results directory does not exist or is empty: {}", resultsDir);
            return;
        }

        boolean generated = false;

        if (isCommandAvailable("allure")) {
            Path tmpOut = projectDir.resolve("target/allure-report-cli");
            deleteRecursively(tmpOut);

            ProcessBuilder pb = new ProcessBuilder(
                    Arrays.asList(
                            "allure",
                            "generate",
                            resultsDir.toString(),
                            "-o",
                            tmpOut.toString(),
                            "--clean"
                    )
            );
            pb.directory(projectDir.toFile());
            pb.inheritIO();

            log.info("Running command: {}", String.join(" ", pb.command()));
            Process process = pb.start();
            int exitCode = process.waitFor();

            if (exitCode == 0 && Files.exists(tmpOut) && !isDirectoryEmpty(tmpOut)) {
                copyDirectory(tmpOut, evidencesLatest);
                generated = true;
                log.info("Allure report generated by CLI and copied to {}", evidencesLatest);
            } else {
                log.warn("Allure CLI failed. Exit code: {}", exitCode);
            }
        }

        if (!generated && isCommandAvailable("mvn")) {
            ProcessBuilder pb = new ProcessBuilder(Arrays.asList("mvn", "allure:report"));
            pb.directory(projectDir.toFile());
            pb.inheritIO();

            log.info("Running command: {}", String.join(" ", pb.command()));
            Process process = pb.start();
            int exitCode = process.waitFor();

            if (exitCode == 0 && Files.exists(generatedReportDir) && !isDirectoryEmpty(generatedReportDir)) {
                copyDirectory(generatedReportDir, evidencesLatest);
                generated = true;
                log.info("Allure report generated by Maven and copied to {}", evidencesLatest);
            } else {
                log.warn("mvn allure:report failed or report directory not found. Exit code: {}", exitCode);
            }
        }

        if (!generated) {
            deleteRecursively(evidencesResults);
            copyDirectory(resultsDir, evidencesResults);
            log.info("Could not generate HTML report; copied raw results to {}", evidencesResults);
        }
    }

    private static boolean isCommandAvailable(String command) {
        try {
            ProcessBuilder pb = new ProcessBuilder(command, "--version");
            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();
            return exitCode == 0;
        } catch (Exception e) {
            log.debug("Command not available: {}", command, e);
            return false;
        }
    }

    private static boolean isDirectoryEmpty(Path path) throws IOException {
        if (!Files.exists(path) || !Files.isDirectory(path)) {
            return true;
        }

        try (var stream = Files.list(path)) {
            return stream.findAny().isEmpty();
        }
    }

    private static void deleteRecursively(Path path) throws IOException {
        if (!Files.exists(path)) {
            return;
        }

        try (var walk = Files.walk(path)) {
            walk.sorted(Comparator.reverseOrder())
                    .forEach(p -> {
                        try {
                            Files.delete(p);
                        } catch (IOException e) {
                            throw new RuntimeException("Failed to delete: " + p, e);
                        }
                    });
        } catch (RuntimeException e) {
            if (e.getCause() instanceof IOException ioException) {
                throw ioException;
            }
            throw e;
        }
    }

    private static void copyDirectory(Path sourceDir, Path targetDir) throws IOException {
        if (!Files.exists(sourceDir)) {
            throw new IOException("Source directory does not exist: " + sourceDir);
        }

        deleteRecursively(targetDir);

        try (var walk = Files.walk(sourceDir)) {
            for (Path source : (Iterable<Path>) walk::iterator) {
                Path target = targetDir.resolve(sourceDir.relativize(source));

                if (Files.isDirectory(source)) {
                    Files.createDirectories(target);
                } else {
                    Path parent = target.getParent();
                    if (parent != null) {
                        Files.createDirectories(parent);
                    }
                    Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
    }
}